[build-system]
requires = [
    "setuptools>=42",
    "requests",
    "dacite",
    "ujson",
    "pyquery==1.4.3",
    "backoff==1.11.1",
    "furl==2.1.3",
    "colorama==0.4.4",
    "lxml==4.7.1"
]
build-backend = "setuptools.build_meta"
